defaults: &defaults
  docker:
    - image: cimg/node:lts

version: 2
jobs:
  percy:
    <<: *defaults
    steps:
      - checkout
      - run:
          # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
          name: Install puppeteer dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y upgrade
            sudo apt-get -yq install gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2t64 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget libgbm-dev
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-node:lts-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn percy
      - save_cache:
          key: yarn-node:lts-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - percy
