name: Cypress chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: cypress-io/github-action@v5
        env:
          CYPRESS_INSTALL_BINARY:
        with:
          start: yarn run start-storybook --port 6006
          wait-on: "http://localhost:6006"
          browser: chrome
          headless: true
          env: port=6006
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
